# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-04 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('sell', '0002_remove_sell_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
