# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-08 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_sell_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpair',
            name='slug',
            field=models.CharField(default='my-slug', max_length=50),
        ),
    ]
