# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-03 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='east_coordinate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='north_coordinate',
            field=models.FloatField(),
        ),
    ]
