# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(default='foobar', max_length=1000)),
            ],
        ),
    ]
