# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-01 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='foobar', max_length=1000),
        ),
    ]
