# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='slug',
            field=models.CharField(default='my-slug', max_length=50),
        ),
    ]
