# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-01 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMessages', '0002_remove_mymessage_conv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='conv_id',
            field=models.IntegerField(null=True),
        ),
    ]
